### PR TITLE
Initialization policy for charged molecules

### PR DESCRIPTION
**Pull request by shaipranesh2**
This PR aims to initialize charge in molecules according to electronegativity. (most eleectronegative atom gets anionic charge and vice versa)

### CODE REVIEW

**Comment by shaipranesh2** [comment]
Btw I wanted to confirm the logic before writing the code entirely here:

1)For the initialization policy, single atoms will get the charge intended unless the charge>number of electrons. 
2)For diatomic molecules,the most electronegative atom will get the anionic charge and the least electronegativity gets cationic charge.
3)For any other multi-atomic molecule, each atom's weighted electronegativity is calculated - i.e atom's electronegativity + (other atom's electronegativity)/(inter-atomic distance). By this I aim to identify most electronegative regions by taking in the neighboring atoms electronegativity too. If 2 or more atoms have similar electronegativity (a very small difference), then charge to be initialized is split accordingly between them.

This might have some problems though, like adding each charge can affect the electronegativity of the atom, and can change the initialization if multiple charges are being added to same atom. I would like get some opinion on this if this has some real effect on our initialization policy.

**Comment by shaipranesh2** [comment]
@dpfau @jsspencer  Btw I wanted to confirm the logic before writing the code entirely here:

1)For the initialization policy, single atoms will get the charge intended unless the charge>number of electrons.
2)For diatomic molecules, the most electronegative atom will get the anionic charge, and the least electronegativity gets a cationic charge.
3)For any other multi-atomic molecule, the most electronegative atom is assigned the anionic charge. In case if there are 2 or more instances of the same atom (most or least electronegative one), then its neighbor's electronegativity is taken into account, i.e. electronegativity of the atom - sum(electronegativity of neighbor/distance from the atom)

This might have some problems though, like adding each charge can affect the atom's electronegativity and can change the initialization if multiple charges are being added to the same atom. One thing which can be done is to make it restricted for an atom to have only one charge , - either +1 or -1, the remaining charges go to the next electronegative atom.
I would like to get some opinion on this initialization policy.

**Comment by jsspencer** [comment]
What problem are you trying to solve? Have you identified a case where the (admittedly simple) initialisation fails? Have you studied existing approaches taken by other QMC packages that might address your needs? Personally, I think such heuristics for initialisation are a bit fragile (e.g. what about HO^{-} and HO^{2-}? What about something like the benzene cation?) and the user can handle initialisation for a custom system manually.

Please note that unfortunately we do not have the capacity to design algorithms which are outside of our own lines of research.

**Comment by shaipranesh2** [comment]
@jsspencer Sorry for the late reply, but would like to take a pick at this  PR again. For starters, can we use mulliken partial charges which comes along with solution computed using PySCF in the training, so would the most negative mulliken charge would accomodate the electron i guess?

**Comment by shaipranesh2** [comment]
@jsspencer @dpfau  Sorry for the late reply, but would like to take a pick at this PR again. For starters, can we use mulliken partial charges which comes along with solution computed using PySCF in the training, so would the most negative mulliken charge would accomodate the electron i guess?

**Pull request closed without merging**
